In [1]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)


[[5 8 9 5 0]
 [0 1 7 6 9]]


In [4]:
import numpy as x
arr=x.random.randint(10,size=(2,5))
print(arr)

[[2 4 5 2 4]
 [2 4 7 7 9]]


In [3]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)

[[5 8 9 5 0]
 [0 1 7 6 9]]


In [5]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)


[[5 8 9 5 0]
 [0 1 7 6 9]]
2


In [6]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)


In [7]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10


In [8]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40


In [9]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9


In [25]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[:2,:3])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
[[5 8 9]
 [0 1 7]]


In [27]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[:,0])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
[5 0]


In [28]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[:,0])
print(arr[0,:])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
[5 0]
[5 8 9 5 0]


In [15]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=(2,5))


print(arr[1])

[0 1 7 6 9]


In [10]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10)
print(arr)

5


In [12]:
import numpy as x

arr=x.random.randint(10)
print(arr)

8


In [20]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=5)


print(arr)

[5 8 9 5 0]


In [22]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=10)


print(arr)

[5 8 9 5 0 0 1 7 6 9]


In [23]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=10)
print(arr)
print(arr[3:9:2])

[5 8 9 5 0 0 1 7 6 9]
[5 0 7]


In [24]:
import numpy as x
x.random.seed(1)
arr=x.random.randint(10,size=10)
print(arr)
print(arr[3:9:2])
print(arr[::-1])

[5 8 9 5 0 0 1 7 6 9]
[5 0 7]
[9 6 7 1 0 0 5 9 8 5]
