In [1]:
import numpy as x
x.array([10,20,30,40,50])


array([10, 20, 30, 40, 50])

In [7]:
import numpy as x
arr = x.array([10,20,30,40,50])
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
import numpy as x
arr = x.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as x
x.empty((2,2))

array([[0.00000000e+000, 8.89101851e-312],
       [8.89101850e-312, 8.89101851e-312]])

In [12]:
import numpy as x
x.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
import numpy as x
x.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])